# Generated by Django 5.1.5 on 2025-06-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchimage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyInstance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("study_id", models.CharField(max_length=255)),
                ("series_id", models.CharField(max_length=255)),
                ("instance_id", models.CharField(max_length=255)),
                ("accession_number", models.CharField(blank=True, max_length=255)),
                ("study_date", models.CharField(blank=True, max_length=20)),
                ("study_description", models.TextField(blank=True)),
                ("patient_id", models.CharField(blank=True, max_length=255)),
                ("patient_name", models.CharField(blank=True, max_length=255)),
                ("patient_sex", models.CharField(blank=True, max_length=10)),
                ("patient_birth_date", models.CharField(blank=True, max_length=20)),
                ("modality", models.CharField(blank=True, max_length=50)),
                ("view_position", models.CharField(blank=True, max_length=50)),
                ("body_part_examined", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("atelectasis", models.FloatField(default=0.0)),
                ("cardiomegaly", models.FloatField(default=0.0)),
                ("consolidation", models.FloatField(default=0.0)),
                ("edema", models.FloatField(default=0.0)),
                ("effusion", models.FloatField(default=0.0)),
                ("emphysema", models.FloatField(default=0.0)),
                ("fibrosis", models.FloatField(default=0.0)),
                ("hernia", models.FloatField(default=0.0)),
                ("infiltration", models.FloatField(default=0.0)),
                ("mass", models.FloatField(default=0.0)),
                ("nodule", models.FloatField(default=0.0)),
                ("pleural_thickening", models.FloatField(default=0.0)),
                ("pneumonia", models.FloatField(default=0.0)),
                ("pneumothorax", models.FloatField(default=0.0)),
                ("enlarged_cardiomediastinum", models.FloatField(default=0.0)),
                ("fracture", models.FloatField(default=0.0)),
                ("lung_lesion", models.FloatField(default=0.0)),
                ("lung_opacity", models.FloatField(default=0.0)),
                (
                    "study_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="fetchimage.studyinstance",
                    ),
                ),
            ],
        ),
    ]
