# Generated by Django 5.1.5 on 2025-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchimage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathologies",
            name="atelectasis",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="cardiomegaly",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="consolidation",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="edema",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="effusion",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="emphysema",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="enlarged_cardiomediastinum",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="fibrosis",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="fracture",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="hernia",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="infiltration",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="lung_lesion",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="lung_opacity",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="mass",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="nodule",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="pleural_thickening",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="pneumonia",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="pathologies",
            name="pneumothorax",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
