# Generated by Django 5.1.5 on 2025-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchimage", "0002_alter_pathologies_atelectasis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklist",
            name="data_set_name",
            field=models.CharField(
                default=" ", max_length=255, verbose_name="Data Set Name"
            ),
            preserve_default=False,
        ),
    ]
