# Generated by Django 5.1.5 on 2025-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchimage", "0002_studyinstance_airesult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyinstance",
            name="status",
            field=models.CharField(default="UNREAD", max_length=50),
        ),
    ]
