# Generated by Django 5.1.5 on 2025-02-24 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchimage", "0003_worklist_data_set_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heatmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("original_img", models.BinaryField(blank=True, null=True)),
                ("pneumothorax", models.BinaryField(blank=True, null=True)),
                ("consolidation", models.BinaryField(blank=True, null=True)),
                (
                    "enlarged_cardiomediastinum",
                    models.BinaryField(blank=True, null=True),
                ),
                ("lung_lesion", models.BinaryField(blank=True, null=True)),
                ("pneumonia", models.BinaryField(blank=True, null=True)),
                ("infiltration", models.BinaryField(blank=True, null=True)),
                ("effusion", models.BinaryField(blank=True, null=True)),
                ("atelectasis", models.BinaryField(blank=True, null=True)),
                ("cardiomegaly", models.BinaryField(blank=True, null=True)),
                ("edema", models.BinaryField(blank=True, null=True)),
                ("lung_opacity", models.BinaryField(blank=True, null=True)),
                ("fracture", models.BinaryField(blank=True, null=True)),
                ("mass", models.BinaryField(blank=True, null=True)),
                ("nodule", models.BinaryField(blank=True, null=True)),
                ("emphysema", models.BinaryField(blank=True, null=True)),
                ("fibrosis", models.BinaryField(blank=True, null=True)),
                ("pleural_thickening", models.BinaryField(blank=True, null=True)),
                ("hernia", models.BinaryField(blank=True, null=True)),
                (
                    "worklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heatmaps",
                        to="fetchimage.worklist",
                    ),
                ),
            ],
        ),
    ]
