# Generated by Django 5.1.5 on 2025-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchimage", "0003_alter_studyinstance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyinstance",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studyinstance",
            name="status",
            field=models.CharField(default="Unread", max_length=50),
        ),
    ]
