# Generated by Django 5.1.5 on 2025-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("RAD", "Radiologist"),
                    ("TECH", "Technician"),
                    ("FRONT", "Front Desk"),
                    ("PHYS", "Referring Physician"),
                ],
                default="FRONT",
                max_length=5,
                verbose_name="User Role",
            ),
        ),
    ]
